# fly.toml app configuration file generated for fastapp on 2023-08-04T15:15:53-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fastapp"
primary_region = "gig"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
